### ISSUE TITLE
Does not cope with multiple instances well.

### ISSUE THREAD

**Issue by kerryland** [osmanovv/auxmic#11]
**"One or errors occurred"**

To reproduce:
* Start auxmic.ui.exe, and use file01.mp4 as the "master" and file02.mp4 as the "other" file. 
* Wait for file02.mp4 to load
* Start auxmic.ui.exe, and use file02.mp4 as the "master". Notice that it loads it more-or-less instantly.
* Load file01.mp4 as the "other" file.

Notice the error dialog that says "One or errors occurred". 

I got into this situation simply because after processing the files the first time I realised I had them the wrong way around, so just ran it again with them the "correct" way around. In truth I don't know what "master" means. Should "master" be renamed to "audio"?

I'd guess it's a problem with name clashes in the temp folder -- maybe add a unique instance identifier to the file names, or just disallow multiple instances of the app :-)

**Comment by osmanovv** [comment]
Hi, Kerry! Thank you for your feedback again : )

I've just fixed this multiple instances running issue. If you don't want to wait until the next release, you can download fixed version from actions section - Artifacts: https://github.com/osmanovv/auxmic/actions/runs/169077570

Yes, that's temp file issue.

Could you please suggest UI improvements in #6. I also don't like current naming, "audio" not suite quite well because it's not neccesary may be an audio, it could be a video media file with better audio as well.
